### ISSUE TITLE
Suitable for testing NOT

### ISSUE THREAD

**Issue by jgwinner** [armbian/documentation#49] opened 2019-07-07 18:46 UTC
I get "not ready for production".

One would, however, expect several variants of a build that is marked "suitable for testing" would at least boot with stock hardware.

If it doesn't boot, then the version posted is the wrong version, as it's clearly not suitable for anything. 

I get "we don't test nightly builds". 

A build that DOES at least boot up, even with known issues, should be available somewhere.

If the build that is posted is expected not to work at all, it should be labeled "experimental" or "nightly" not "suitable for testing"

I would expect two things:

"Suitable for testing" changed to  "nightly" or "experimental - unstable"
two:
A version that did at least boot up be posted somewhere, and marked "last known testable version" or other more accurate label.

People can't contribute in the slightest if there is no version available that does anything but create very tiny paperweights. 

And a final note, I'm trying to contribute, but when the support thread gets moved and locked,  ...  how do you expect people to contribute?

I can't even test multiple versions and post which one works!

**Comment by igorpecovnik** [comment] 2019-07-07 20:13
Thank you for expression your concerns.

A few people that are around the project can't possibly have that precise overview on kernel development on many different platforms to be able to provide you such information. Even on one is impossible. Each person at best can know the state of one single functionality and only if you talk to that person you know. If you want to understand how far this and that feature are, you have talk to or observe many people (activity) which is very time consuming. It is already very hard to know which kernel is in which state - to provide public some usable information: "experimental, testing, stable". Remember, we are an amateur force. Solo that is not the biggest problem. It's also stupid to waste precious resources to get a grip on a moving target if you actually don't have the time/money/people to fix thousands of problems that are found. Further. Explaining this extreme changeable situation to end users (we are not a media corporation so we can't/don't know how to do that) is futile and figuring out who end users is and who is developer is yet another challenging task ... among those "1000+" on the list.

Armbian is a community project. When you bring problems up, you are talking to everyone and you are the one who will solve them. Or not. I don't need that any of those boards works more than you do. How we will get there is at best equally problematic for you as it is for me.

If you want to level up kernel development or change process to better, you are welcome to do something about. Check forum threads as such: 

- https://forum.armbian.com/topic/10841-the-testing-thread/ 
- https://forum.armbian.com/topic/6281-board-support-general-discussion-project-aims/
- https://forum.armbian.com/topic/9031-rfc-001-changes-for-boards-and-features-implementing/

to understand what problems we have, what we already tried, what we didn't and what we are planning to do to make things better. Hopefully.

**Comment by jgwinner** [comment] 2019-07-07 20:39
Can we stay on topic?

Someone typed up the HTML to mark it as "Ready for testing".
 
It's not. Don't mark it that way. The webpage at:
https://www.armbian.com/pine-h64/
sets up false expectations.

Start off by labeling it "Experimental" and make a note that it may or may not even boot. 

That's the Doc bug. It's not my release procedure; I'm providing feedback to you, and begging you to fix a broken process.

I mean, how do you expect me to contribute? I downloaded every single version available and none of them worked.

**Comment by igorpecovnik** [comment] 2019-07-07 21:11
> sets up false expectations.

That's your (miss)interpretation. We have hundreds of thousands of users and most people get it right. We did a lot of study on this to make support pressure/costs as low as possible. FAQ on that every same page:

> SUPPORTED devices are tested and they work apart from known issues and missing features. Support is provided as far as possible (in general there is no support for 3rd party hardware like DVB tuners and software like Kodi). Please check the documentation and existing forum posts before posting a question. Questions on private channels are ignored. 

> **SUITABLE FOR TESTING (WIP) are devices which we’re currently working on but they are not ready! These images are suitable for developers and experienced users. They are not very well tested but they might work without any problems. Your help to improve this situation is greatly appreciated.** 

> SUPPORT ENDED (EOS) status are devices which used to be supported in the past. Reasons for moving to this section:
no active software development (mainline u-boot and kernel)
no support from the vendor (hardware samples, documentation, software packages)
never was sold, only samples in small quantities were available
hardware design flaws don’t allow using these devices without stability issues
Support status:
images are stable but we don’t test updating,
images are provided with no support,
most images have frozen kernel and u-boot packages to prevent their upgrades.
> NO OFFICIAL SUPPORT (CSC) are devices which are supported by the 3rd party. We usually don't have hardware samples nor conduct any tests but they might work. There is no support whatsoever.

> and begging you to fix a broken process

I don't work for you.

> how do you expect me to contribute?

This is opensource project. Your contribution to the Linux kernel is public, not mine.

> I downloaded every single version available and none of them worked.

Next time read FAQ first and there is no support for such builds. Even for stable is only our good will.

**Comment by igorpecovnik** [comment] 2019-07-07 21:16
BTW. I boot this board today so I can confirm that images from the download section works.

**Comment by jgwinner** [comment] 2019-07-09 04:10
Good to hear you can boot. What specific hardware?

Mine still doesn't. I posted details,.

It's really simple. I download what you say is ready to test, I test, I get a hung board. I post about it.

You tell me it's not guaranteed to boot.

So, I'm saying modify "ready to test" to "experimental". 

If you mean it is ready to test, and it should work, then it's due some debugging, not just dismissal of "it doesn't work" or:

> most people get it right. 

Ah. I get it. An ad-hominem attack? lol. At least one other person on the forum had the same problem.

**Comment by igorpecovnik** [comment] 2019-07-09 06:45
> What specific hardware?

Pine with H6
https://www.armbian.com/pine-h64/

> I test, I get a hung board. 

Discussing about boards for testing is limited to community "members". This one way to deal with "spam"/pressure. You need 5 usable posts on the forum (those here doesn't count). "Your" overall financial contribution in covering support costs (without R&D and anything else) is way below 1% which means we set the rules. I am aware that it is possible to loose some important parts and people, because of this, but limiting support pressure is the only way that we don't burst into flames. When you get that, you get a chance to be addressed.

>So, I'm saying modify "ready to test" to "experimental".

I might be listening if this would come from people that I work with or from substantial number of people that could be trusted. I see you do have some experience, so I am talking your note seriously. But since problem is not possible to recreate and "ready to test" boards boots in 95% of the time there is no need to change anything or discuss this matter. Perhaps you are doing some novice mistake? I also do it sometime. If this is so, you need to change something, perhaps a hardware - we didn't make in 1st place - is broken? 

> I post about it.

We have forum section for that. If you post elsewhere, like here, its possible that nobody will be noticing and for sure nobody will react. Even on forum there are very slim chances. Once again. I would like to hear from your troubles to be able to fix them, but we simply can't serve so many users with few people and entirely on our costs. Its a suicide. If you don't care about this, why should I/we?

> An ad-hominem attack? 

Just plain statistic. Can now this "issue" be closed?

**Comment by jgwinner** [comment] 2019-07-10 02:32
This doc bug was opened with the request to add a "last known good" link in addition to the current 'Ready for testing' link as you mentioned that may or may not work. If you don't want to do that, you can close this doc bug. 

To the larger issue ...  

> https://www.armbian.com/pine-h64/

A or B? The H64 model B is what is sold on the store. You linked the "A" board. Maybe there's a difference.  

I and one other forum member are using the current board, and it's not working.

So I think it's possible it's not a 95% success rate. 

I just did it again; AOSC works *perfectly* and Ubunto locks. Over 8 times 100% failure, 6 O/S's and 2 SD Cards. I'll follow up with the Pine64HW folks and forum (although it's probably not hardware, unless Armbian uses more of it than AOSC).

**Comment by igorpecovnik** [comment] 2019-07-10 03:13
> This doc bug was opened with the request to add a "last known good" link in addition to the current 'Ready for testing' link as you mentioned that may or may not work. If you don't want to do that, you can close this doc bug.

It is to expensive to provide real time data about the support status for in development hw. Things are rapidly changing all the time and this level of service is simply not possible to cover. I am sorry.

> A or B? The H64 model B is what is sold on the store. You linked the "A" board. Maybe there's a difference.

There are picture of devices on the download pages ... for a reason.

You are using a board that we don't support at all (even it could just work) and you wasted few hours of my time for nothing at all? Now you do understand why communication is initially always treated as spam. In most cases, users are lazy or abusive. 

> To the larger issue ...

Sure. Bard support costs are estimated to start at 20.000 EUR/year and you and neither HW maker pays virtually nothing. Solo this is a reason to do absolutely nothing when it comes to add support for yet another hardware. Use Android or whatever junk is supplied by the board maker. Perhaps this is the only way that a difference can be spotted. 

Now I have a legitimate reason for closing.

**Closed by igorpecovnik** 2019-07-10 03:13 UTC

**Comment by jgwinner** [comment] 2019-07-10 04:15
> It is to expensive to provide real time data about the support status for in development hw. Things are rapidly changing all the time and this level of service is simply not possible to cover. I am sorry.

I'm not asking for that. I'm asking for ONE STATIC HTML LINE with a link to a known good configuration. Many open source projects do that.

> There are picture of devices on the download pages ... for a reason.

Exactly my point. If you had established specifics when posting "I got it to run," specifically on what, or on the web page, this would have been much shorter.

Your "Suitable for testing" page is missing a lot of detail. You should provide it. That's a doc bug. 

So you're mad because you are building a target for a board that is unavailable and will never be available?

Build software for devices that can't be purchased. Good luck with that.

**Comment by jgwinner** [comment] 2019-07-10 04:29
I just checked. The first line of my first post to you specifically mentioned I was using the H64 "B" board.

No need to "look at photos" maybe you should be more specific. I was.
